[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"

[build]
  command = "cd .. ; mv repo repo2 ; ln / -s repo ; find /opt/build -name '*#*' | xargs rm -rf"
  functions = "netlify/functions"
  publish = "/opt/build"

[context.deploy-preview]
  command = "yarn build:preview"
